// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {printer} from '../models';
import {monitor} from '../models';
import {main} from '../models';

export function AddMonitorTask(arg1:string):Promise<void>;

export function DefaultPrintParams():Promise<printer.PrintParams>;

export function GetMonitorConfig():Promise<monitor.Config>;

export function GetMonitorStatus():Promise<Record<string, monitor.TaskStatus>>;

export function GetPrinterJobs(arg1:string):Promise<Array<main.PrintJob>>;

export function GetPrinterStatus(arg1:string):Promise<main.PrinterStatus>;

export function HideWindow():Promise<void>;

export function IsFinePrintMonitorEnabled():Promise<boolean>;

export function IsFinePrintMonitorRunning():Promise<boolean>;

export function NotifyPrintResult(arg1:printer.PrintResult):Promise<void>;

export function ParseCURL(arg1:string):Promise<monitor.ParsedRequest>;

export function PausePrinter(arg1:string):Promise<void>;

export function QuitApp():Promise<void>;

export function ReloadMonitor():Promise<void>;

export function RemoveMonitorTask(arg1:string):Promise<void>;

export function RemovePrintJob(arg1:string,arg2:number):Promise<void>;

export function ResumePrinter(arg1:string):Promise<void>;

export function SaveMonitorConfig(arg1:string):Promise<void>;

export function ShowWindow():Promise<void>;

export function StartFinePrintMonitor():Promise<void>;

export function StartPrint(arg1:printer.PrintParams):Promise<printer.PrintResult>;

export function StopFinePrintMonitor():Promise<void>;

export function TestPushPlus(arg1:string,arg2:string,arg3:string):Promise<void>;

export function UpdateMonitorTask(arg1:string):Promise<void>;
