// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {printer} from '../models';
import {main} from '../models';

export function DefaultPrintParams():Promise<printer.PrintParams>;

export function GetPrinterJobs(arg1:string):Promise<Array<main.PrintJob>>;

export function NotifyPrintResult(arg1:printer.PrintResult):Promise<void>;

export function PausePrinter(arg1:string):Promise<void>;

export function StartPrint(arg1:printer.PrintParams):Promise<printer.PrintResult>;
