// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddMonitorTask(arg1) {
  return window['go']['main']['App']['AddMonitorTask'](arg1);
}

export function DefaultPrintParams() {
  return window['go']['main']['App']['DefaultPrintParams']();
}

export function GetMonitorConfig() {
  return window['go']['main']['App']['GetMonitorConfig']();
}

export function GetMonitorStatus() {
  return window['go']['main']['App']['GetMonitorStatus']();
}

export function GetPrinterJobs(arg1) {
  return window['go']['main']['App']['GetPrinterJobs'](arg1);
}

export function GetPrinterStatus(arg1) {
  return window['go']['main']['App']['GetPrinterStatus'](arg1);
}

export function HideWindow() {
  return window['go']['main']['App']['HideWindow']();
}

export function IsFinePrintMonitorEnabled() {
  return window['go']['main']['App']['IsFinePrintMonitorEnabled']();
}

export function IsFinePrintMonitorRunning() {
  return window['go']['main']['App']['IsFinePrintMonitorRunning']();
}

export function NotifyPrintResult(arg1) {
  return window['go']['main']['App']['NotifyPrintResult'](arg1);
}

export function ParseCURL(arg1) {
  return window['go']['main']['App']['ParseCURL'](arg1);
}

export function PausePrinter(arg1) {
  return window['go']['main']['App']['PausePrinter'](arg1);
}

export function QuitApp() {
  return window['go']['main']['App']['QuitApp']();
}

export function ReloadMonitor() {
  return window['go']['main']['App']['ReloadMonitor']();
}

export function RemoveMonitorTask(arg1) {
  return window['go']['main']['App']['RemoveMonitorTask'](arg1);
}

export function RemovePrintJob(arg1, arg2) {
  return window['go']['main']['App']['RemovePrintJob'](arg1, arg2);
}

export function ResumePrinter(arg1) {
  return window['go']['main']['App']['ResumePrinter'](arg1);
}

export function SaveMonitorConfig(arg1) {
  return window['go']['main']['App']['SaveMonitorConfig'](arg1);
}

export function ShowWindow() {
  return window['go']['main']['App']['ShowWindow']();
}

export function StartFinePrintMonitor() {
  return window['go']['main']['App']['StartFinePrintMonitor']();
}

export function StartPrint(arg1) {
  return window['go']['main']['App']['StartPrint'](arg1);
}

export function StopFinePrintMonitor() {
  return window['go']['main']['App']['StopFinePrintMonitor']();
}

export function TestPushPlus(arg1, arg2, arg3) {
  return window['go']['main']['App']['TestPushPlus'](arg1, arg2, arg3);
}

export function UpdateMonitorTask(arg1) {
  return window['go']['main']['App']['UpdateMonitorTask'](arg1);
}
