// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DefaultPrintParams() {
  return window['go']['main']['App']['DefaultPrintParams']();
}

export function NotifyPrintResult(arg1) {
  return window['go']['main']['App']['NotifyPrintResult'](arg1);
}

export function StartPrint(arg1) {
  return window['go']['main']['App']['StartPrint'](arg1);
}
